Make it possible for CI to fail

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -19,4 +19,12 @@ jobs:
       - name: Install dependencies
         run: python -m pip install --upgrade pip pyflakes
       - name: Pyflakes
-        run: find -name '*.py' -exec pyflakes {} \;
+        run: |
+          errors=$(find -name '*.py' -exec pyflakes {} +)
+          echo "$errors"
+          if [[ -z "$errors" ]];
+            exit 0
+          else;
+            exit 1
+          done
+        continue-on-error: true
